### PR TITLE
Automatically poll for multiple assets

### LINKED ISSUE #10: Pull in newly create DIPs upon rerun
Rerun looks good. 

TODO: Allow for new DIP listening within a rerun. New SOL DIP listening seems to only work with a hard restart

_Originally posted by @DonDuala in https://github.com/Dual-Finance/risk-manager/issues/9#issuecomment-1215604483_

### LINKED ISSUE #11: Support BTC & ETH Automating Polling
Currently only SOL DIPs are polled automatically. Add BTC & ETH with rerun logic, so a DIP can be added while running and it doesn't require a hard restart too

### PR DESCRIPTION
**Pull request by brittcyr**
Fixes #10 Fixes #11

### CODE REVIEW

**Comment by DonDuala** [comment]
Tested creating a new BTC DIP and staking to it.

BTC DIP automatically gets tracked correctly, but it missed the deposit. 

https://solscan.io/tx/5tGFsLjg41MtAXwDxD967SCQ8Fd7FBQqocJkk1r2awDCg3wAM7Kqv7pB318N1HnDBQGmPUDb9ybMBWMKvrY35Jtp

image

**Comment by DonDuala** [comment]
> Tested creating a new BTC DIP and staking to it.
> 
> BTC DIP automatically gets tracked correctly, but it missed the deposit.
> 
> Correctly, manges the BTC DIP deposit only upon hard restart
> 
> https://solscan.io/tx/5tGFsLjg41MtAXwDxD967SCQ8Fd7FBQqocJkk1r2awDCg3wAM7Kqv7pB318N1HnDBQGmPUDb9ybMBWMKvrY35Jtp
> 
> image

@brittcyr let's address this before merging

**Comment by brittcyr** [comment]
Did you deposit before the next 10 minute polling interval or after?

**Comment by brittcyr** [comment]
Screen Shot 2022-08-16 at 8 40 04 PM
Worked for me. Did it correct on the next update?

**Comment by DonDuala** [comment]
Did not correct itself after the next update. I will try to replicate the behavior

**Comment by DonDuala** [comment]
Replicated by
1. Run main
2. Create new DIP
3. Wait for rerun to cycle so new DIP is listened to
4. Stake to new DIP
-> No deposit event is recorded or triggered even after the scalper window expires and rerun occurs

**Comment by brittcyr** [comment]
Likely the issue is that the RPC proxy times out and gets a 504, so it misses the subscription updates.
The refresh of DIPs every 10 minutes only updates the list, not the balances. I changed that to also do the balances every 10 minutes in case the subscription fails

**Comment by DonDuala** [comment]
image

Duplication of DIP, 2nd run thru it dupes the risk as well

**Comment by DonDuala** [comment]
Still working through how to best manage the processes upon a new scalper run

**Review by DonDuala — APPROVED** [review]

**Pull request merged**
