### PR TITLE
Rerun

### PR DESCRIPTION
**Pull request by brittcyr**

### CODE REVIEW

**Comment by brittcyr** [comment]
Are scalper window in the scalper code and the min frequency that we rerun the trading code necessarily the same? not sure, they might be, but if not, use two variables

**Comment by DonDuala** [comment]
Scalper window should always equal the rerun window

**Comment by DonDuala** [comment]
Current version doesnt seem to pull in the current open DIP position. Should be .098 of the SOL $45 8/26/2022 DIP

**Comment by brittcyr** [comment]
Is it getting the wrong number, or not getting anything?
Which config is that position on?

**Comment by DonDuala** [comment]
Not getting anything upon the first run (doesn't pull the SOL DIP) then pulls but with 0 quantity 
image

**Comment by DonDuala** [comment]
image

**Comment by DonDuala** [comment]
Looks actually like the above pool was the old one without the 1000x expiration time multiplier. But it should pull in this one without needing a deposit:
image

**Comment by brittcyr** [comment]
It only updates when there is a deposit. Need to do a cold restart, will add that to this change

**Comment by DonDuala** [comment]
Upon start it doesn't get the correct delta position
image

We keep flipping back and forth that delta each time we test

**Comment by DonDuala** [comment]
Rerun looks good. 

TODO: Allow for new DIP listening within a rerun. New SOL DIP listening seems to only work with a hard restart

**Review by DonDuala — APPROVED** [review]

**Pull request merged**
